name: .NET

on:
  push:
    branches: [master]
  #pull_request:
  #  branches: [master]

env:
  PACKAGE_TOKEN: ${{secrets.PACKAGE_TOKEN}}
  PACKAGE_TOKEN_NUGET: ${{secrets.NUGET_API_KEY}}
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Pack
        run: dotnet pack HtmlMailControlWpf --configuration Release -o artifacts/

      - name: GitHub Package Authorization
        run: dotnet nuget add source --username YoshikazuArimitsu --password "$env:PACKAGE_TOKEN" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/YoshikazuArimitsu/index.json"

      #- name: Publish GitHub
      #  run: dotnet nuget push "artifacts/HtmlMailControlWpf.0.0.16.nupkg" --api-key "$env:PACKAGE_TOKEN" --source "github"

      - name: Publish to NuGet
        run: dotnet nuget push "artifacts/HtmlMailControlWpf.0.0.16.nupkg" --api-key "$env:PACKAGE_TOKEN_NUGET" --source https://api.nuget.org/v3/index.json
